insert into people (name, age, profession) values ('Patten', 49, 'VP Marketing');
insert into people (name, age, profession) values ('Lynnea', 37, 'Associate Professor');
insert into people (name, age, profession) values ('Wilek', 41, 'Food Chemist');
insert into people (name, age, profession) values ('Starlene', 52, 'Senior Sales Associate');
insert into people (name, age, profession) values ('Dora', 29, 'Research Associate');
insert into people (name, age, profession) values ('Buiron', 64, 'Computer Systems Analyst IV');
insert into people (name, age, profession) values ('Millie', 25, 'VP Sales');
insert into people (name, age, profession) values ('Morgan', 90, 'Automation Specialist II');
insert into people (name, age, profession) values ('Ofella', 77, 'Mechanical Systems Engineer');
insert into people (name, age, profession) values ('Marian', 55, 'Technical Writer');
insert into people (name, age, profession) values ('Edeline', 16, 'VP Product Management');
insert into people (name, age, profession) values ('Raffaello', 16, 'Food Chemist');
insert into people (name, age, profession) values ('Tore', 90, 'Automation Specialist IV');
insert into people (name, age, profession) values ('Jessika', 78, 'Operator');
insert into people (name, age, profession) values ('Manda', 46, 'Paralegal');
insert into people (name, age, profession) values ('Eve', 75, 'Design Engineer');
insert into people (name, age, profession) values ('Ram', 83, 'Actuary');
insert into people (name, age, profession) values ('Dot', 13, 'Civil Engineer');
insert into people (name, age, profession) values ('Ogden', 88, 'Staff Accountant IV');
insert into people (name, age, profession) values ('Fidelio', 63, 'Payment Adjustment Coordinator');
