insert into people (name, age, profession, hobbies) values ('Mallorie', 21, 'Staff Accountant IV', 'Pied crow');
insert into people (name, age, profession, hobbies) values ('Nonah', 67, 'Web Developer III', 'Kingfisher, malachite');
insert into people (name, age, profession, hobbies) values ('Halsey', 56, 'Mechanical Systems Engineer', 'Pintail, white-cheeked');
insert into people (name, age, profession, hobbies) values ('Zulema', 80, 'Financial Advisor', 'Eagle, pallas''s fish');
insert into people (name, age, profession, hobbies) values ('Annadiane', 82, 'Environmental Specialist', 'Squirrel, malabar');
insert into people (name, age, profession, hobbies) values ('Aleece', 48, 'Electrical Engineer', 'Asian foreset tortoise');
insert into people (name, age, profession, hobbies) values ('Delila', 30, 'Quality Engineer', 'Brown and yellow marshbird');
insert into people (name, age, profession, hobbies) values ('Augustine', 24, 'GIS Technical Architect', 'Tyrant flycatcher');
insert into people (name, age, profession, hobbies) values ('Sisely', 41, 'Information Systems Manager', 'Pheasant, common');
insert into people (name, age, profession, hobbies) values ('Lothario', 24, 'Director of Sales', 'Red meerkat');
insert into people (name, age, profession, hobbies) values ('Annadiane', 78, 'VP Quality Control', 'Large cormorant');
insert into people (name, age, profession, hobbies) values ('Branden', 36, 'Web Developer IV', 'White-faced whistling duck');
insert into people (name, age, profession, hobbies) values ('Linea', 87, 'Research Assistant II', 'Grey mouse lemur');
insert into people (name, age, profession, hobbies) values ('Kara', 85, 'Office Assistant IV', 'Kalahari scrub robin');
insert into people (name, age, profession, hobbies) values ('Alexandra', 41, 'Nurse', 'Palm squirrel');
insert into people (name, age, profession, hobbies) values ('Lyda', 80, 'Technical Writer', 'Raccoon, crab-eating');
insert into people (name, age, profession, hobbies) values ('Rudolfo', 90, 'Web Developer II', 'Saddle-billed stork');
insert into people (name, age, profession, hobbies) values ('Bailey', 41, 'Human Resources Assistant IV', 'Sun gazer');
insert into people (name, age, profession, hobbies) values ('Shelby', 51, 'Professor', 'Cat, long-tailed spotted');
insert into people (name, age, profession, hobbies) values ('Kacy', 59, 'Professor', 'Weaver, sociable');
